import { motion } from 'framer-motion';
import { Cpu, ChevronRight, CheckCircle, AlertCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { aiInsight } from '../data/mockData';

export default function AIInsightCard() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 14 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.3 }}
      className="gov-card p-5 border-l-4 border-l-gov-blue"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-gov bg-gov-blue-light border border-blue-200 flex items-center justify-center">
            <Cpu size={16} className="text-gov-blue" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gov-navy">AI Competency Insight</h3>
            <p className="text-[10px] text-gov-gray-400">Generated on {aiInsight.generatedOn} · Based on your assessment results</p>
          </div>
        </div>
        <span className="badge-gov-info text-[10px]">
          <span className="w-1.5 h-1.5 rounded-full bg-gov-blue animate-pulse" />
          AI Analysis
        </span>
      </div>

      {/* Main insight */}
      <div className="bg-gov-off-white border border-gov-gray-200 rounded-gov p-4 mb-4">
        <p className="text-sm text-gov-gray-600 leading-relaxed italic">
          "{aiInsight.summary}"
        </p>
      </div>

      {/* Strengths & Priorities */}
      <div className="grid sm:grid-cols-2 gap-3 mb-4">
        <div className="bg-gov-green-light border border-green-200 rounded-gov p-3">
          <p className="text-[10px] font-semibold text-gov-green uppercase tracking-wide mb-2 flex items-center gap-1">
            <CheckCircle size={10} /> Strengths
          </p>
          <ul className="space-y-1">
            {aiInsight.strengths.map(s => (
              <li key={s} className="text-xs text-gov-gray-700 flex items-center gap-1.5">
                <div className="w-1 h-1 rounded-full bg-gov-green shrink-0" />
                {s}
              </li>
            ))}
          </ul>
        </div>
        <div className="bg-gov-red-light border border-red-200 rounded-gov p-3">
          <p className="text-[10px] font-semibold text-gov-red uppercase tracking-wide mb-2 flex items-center gap-1">
            <AlertCircle size={10} /> Priority Gaps
          </p>
          <ul className="space-y-1">
            {aiInsight.priorityGaps.map(g => (
              <li key={g} className="text-xs text-gov-gray-700 flex items-center gap-1.5">
                <div className="w-1 h-1 rounded-full bg-gov-red shrink-0" />
                {g}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Recommendation */}
      <div className="bg-gov-amber-light border border-amber-200 rounded-gov px-4 py-2.5 mb-4">
        <p className="text-[10px] font-semibold text-gov-amber uppercase tracking-wide mb-0.5">Recommendation</p>
        <p className="text-xs text-gov-gray-700">{aiInsight.recommendation}</p>
      </div>

      <Link to="/competencies" className="btn-gov-secondary w-full justify-center text-xs py-2.5">
        View Detailed Analysis <ChevronRight size={12} />
      </Link>

      {/* Disclaimer */}
      <p className="text-[9px] text-gov-gray-400 text-center mt-2 leading-tight">
        This insight is generated by the AI analysis engine. For official evaluation, contact your reporting officer.
      </p>
    </motion.div>
  );
}
